- hosts: localhost
  gather_facts: no
  tasks:
  - hue_group:
      bridge: 192.168.254.100
      lights:
      - l1
      - l2
      - l3
      name: Test1
  - hue_group:
      bridge: 192.168.254.100
      lights:
      - l4
      - l5
      - l6
      name: Test2

