- hosts: localhost
  gather_facts: no
  vars:
    on_state:
      "on": true
      "bri": 120
      "xy": [0.5701, 0.313]
  tasks:
  - uri:
      url: "http://192.168.254.100/api/12345-luggage/lights/{{item}}/state"
      method: PUT
      body: ' {{on_state|to_json}}'
    with_sequence: start=1 end=6

