- hosts: localhost
  gather_facts: no
  vars:
    on_state:
      "on": true
      "bri": 200
      "xy": [0.4448, 0.4066]
    off_state:
      "on": false
  tasks:
  - uri:
      url: "http://192.168.254.100/api/12345-luggage/lights/{{item}}/state"
      method: PUT
      body: ' {{on_state|to_json}}'
    with_sequence: start=1 end=6
    when: state is defined and state == 'on'

  - uri:
      url: "http://192.168.254.100/api/12345-luggage/lights/{{item}}/state"
      method: PUT
      body: ' {{off_state|to_json}}'
    with_sequence: start=1 end=6
    when: state is defined and state == 'off'

